branches:
  only:
    - master

language: generic
matrix:
  include:
    - &swiftpm_linux
      name: SwiftPM / Linux / Swift 5.0.3
      os: linux
      dist: trusty
      sudo: required
      env:
        - SWIFT_VERSION=5.0.3
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - ./test swiftpm
    - <<: *swiftpm_linux
      name: SwiftPM / Linux / Swift 5.1 Development
      env:
        - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-09-09-a
install: true
script:
  - ./test $TYPE

notifications:
  email: false
