name: CI (Xcode)

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  xcode:
    name: Xcode ${{ matrix.xcode }} - ${{ matrix.platform }}
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [11.7, 12.4, 12.5]
        platform: [macos, ios, tvos]
      fail-fast: false
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v2
      - run: ./test ${{ matrix.platform }}
      - run: ./test ${{ matrix.platform }}_xcodespm
