name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  xcode:
    name: Xcode ${{ matrix.xcode }} - ${{ matrix.platform }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11, 11.1, 11.2]
        platform: [macos, ios, tvos]
    steps:
    - uses: actions/checkout@v1
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test ${{ matrix.platform }}

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11, 11.1, 11.2]
    steps:
    - uses: actions/checkout@v1
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test swiftpm
